server:
  port: 8080
  servlet:
    context-path: /imomsw

spring:
  application:
    name: Port

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://<DB_HOST>:5432/<DB_NAME>
    username: <DB_USERNAME>
    password: <DB_PASSWORD>

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: imo_jit


master-data:
  baseUrl: https://demo-spocp.app.pomfret.cloud/api/public/verificationdata


fileflow:
  baseUrl: https://demo-spocp.app.pomfret.cloud/api
  pdfgenerationpath: /fileflow/template/


auth:
  username: <AUTH_USERNAME>
  password: <AUTH_PASSWORD>





